### ISSUE TITLE
MakeItem.dbc issue

### ISSUE THREAD

**Issue by Asandru** [TrinityItemCreator/TrinityItemCreator#6]
**Current Issue:** Is not updating item.dbc but instead is just extracting items from database which is not complete.

**How to fix** Just copy itemdata.dbc from data/itemdata.dbc and add new rows from database if items are custom or replace existing item.dbc items

**Comment by Hobbilis** [comment]
Hey Asandru, I suggest you to contact https://github.com/Mitch528
I believe he can help you, he knows his way around this.

**Comment by Asandru** [comment]
@Hobbilis Thanks, I sent him an email.

**Comment by Asandru** [comment]
Fixed.
